import os

INVESTOR_APP_PATH = os.environ.get("INVESTOR_APP_PATH")
INVESTOR_APP_ENVIRONMENT = os.environ.get("INVESTOR_APP_ENVIRONMENT")
INVESTOR_APP_DB_CONNECTION = f"sqlite:///{INVESTOR_APP_PATH}"

CRYPTO_BASE_URL = "https://api.crypto.com/exchange/v1/"
CRYPTO_MARKET_URL = f"{CRYPTO_BASE_URL}public/"
CRYPTO_USER_URL = f"{CRYPTO_BASE_URL}private/"

CRYPTO_KEY = os.environ.get("CRYPTO_KEY")
CRYPTO_SECRET_KEY = os.environ.get("CRYPTO_SECRET_KEY")

INVESTMENT_INCREMENTS = 5
MAX_COINS = 4
